### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by taylormusolf** [zoumus/Bel-Chocolate#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page
## Comments
---
# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from your MPV list
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one full CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points
## Comments
- Update your MVP's to be 7 main MVP's and the rest as bonus.

---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- you shouldn't need `price` in `cart_items` since it is already in `products`
- in `reviews` you mention in bullets `teas`?
- some `bigint` datatypes should be `integer` like quantity and rating.
- remove `product_id` from `categories` table as you already have foreign key for `category_id` in `products` table
---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
 - comma missing after `reviews` object
 - no `product_id` in `categories`
 - make sure to camelCase all keys
 - make sure only referencing id's to other tables
---
# Backend Routes
- [x] Contains the following section: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
- need a show route for Session
- won't need a reviews GET route as you should get that information when you do your products show GET route
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)
## Comments
- check your formatting
- wildcards should have ":"

**Comment by zoumus** [comment]
Hi taylor,
for the comment MVP, i was just thinking to add comment feature where a user can add that with a review. i guess i'll need to add comments table but we can discuss that later.
thank you.

**Comment by zoumus** [comment]
Hi Taylor,
for the comment MVP i was just thinking that the user can add a comment attached to the review, i guess i don't need that because my review table can handle that,
We'll discuss that later.
thank you

**Comment by taylormusolf** [comment]
Added more feedback for you
